# Generated by Django 3.0.7 on 2020-07-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='photos', to='myapp.Photo'),
        ),
    ]
