# Generated by Django 3.0.7 on 2020-07-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200724_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ManyToManyField(blank=True, to='myapp.Photo'),
        ),
    ]
