# Generated by Django 3.0.7 on 2020-07-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200724_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
