# Generated by Django 3.0.7 on 2020-07-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200724_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profile_image'),
        ),
    ]
